version: "3.5"

services:
  mongodb:
    container_name: mongodb_container
    build:
      context: ./mongodb
    ports:
      - 969:27017
    # network: host
    command: mongod
  api:
    container_name: api_container
    restart: always
    build:
      context: ./api
    ports:
      - "4321:4321"
    depends_on:
      - "mongodb"
  nginx:
    container_name: nginx_container
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - "api"
      - "mongodb"
