version: "3.5"

services:
  mongodb_test:
    container_name: mongodb_test_container
    build:
      context: ./mongodb
    ports:
      - 969:27017
    # network: host
    command: mongod
  api_test:
    container_name: api_test_container
    restart: always
    build:
      context: ./api
    ports:
      - "4321:4321"
    depends_on:
      - "mongodb_test"
  nginx_test:
    container_name: nginx_test_container
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - "api_test"
      - "mongodb_test"
